version: "3.7"
services:
  placemanager-server:
    build:
      context: .
      dockerfile: ./placemanager-server/Dockerfile
    restart: on-failure
    image: placemanager-server
    container_name: placemanager-server
    env_file: env.list
  rest-server:
    build:
      context: .
      dockerfile: ./rest-server/Dockerfile
    restart: on-failure
    image: rest-server
    container_name: rest-server
    env_file: env.list