version: "3.7"
services:
  placemanager-server:
    build: ./placemanager-server
    restart: on-failure
    image: placemanager-server
    container_name: placemanager-server
    env_file: env.list
  rest-server:
    build: ./rest-server
    restart: on-failure
    image: rest-server
    container_name: rest-server
    env_file: env.list